import { getProducts, createProduct, updateProduct, deleteProduct } from './api.js';
const $ = (selector, scope = document) => scope.querySelector(selector);
const $$ = (selector, scope = document) => [...scope.querySelectorAll(selector)];
const state = { products: [], category: 'all', query: '', sort: 'featured', cart: readStorage('northstar-cart', []), saved: readStorage('northstar-saved', []), signedIn: readStorage('northstar-demo-session', false), external: new URLSearchParams(location.search).get('source') === 'external' };
function readStorage(key, fallback) { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } }
function saveStorage(key, value) { try { localStorage.setItem(key, JSON.stringify(value)); } catch { announce('Could not save your preference in this browser.'); } }
const money = amount => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(Number(amount) || 0);
const safe = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
const categoryLabel = value => ({ "women's clothing": 'Objects', jewelery: 'Accessories', electronics: 'Technology' })[value] ?? value;
function announce(message) { const toast = $('#toast'); toast.textContent = message; toast.classList.add('show'); clearTimeout(announce.timer); announce.timer = setTimeout(() => toast.classList.remove('show'), 2300); }
function visibleProducts() { let list = [...state.products]; if (state.category !== 'all') list = list.filter(item => item.category === state.category); if (state.query) list = list.filter(item => `${item.title} ${item.category} ${item.description}`.toLowerCase().includes(state.query)); if (state.sort === 'price-asc') list.sort((a,b) => a.price-b.price); if (state.sort === 'price-desc') list.sort((a,b) => b.price-a.price); if (state.sort === 'rating') list.sort((a,b) => (b.rating?.rate||0)-(a.rating?.rate||0)); return list; }
function renderProducts() { const list = visibleProducts(); $('#product-grid').setAttribute('aria-busy','false'); $('#product-grid').innerHTML = list.map((item,index) => `<article class="product-card"><div class="product-image"><img src="${safe(item.image)}" alt="${safe(item.title)}" loading="lazy"><span class="product-tag">${index===0?'A GOOD FIND':'THOUGHTFULLY PICKED'}</span><button class="product-wish" type="button" aria-label="${state.saved.includes(item.id)?'Remove':'Save'} ${safe(item.title)}" aria-pressed="${state.saved.includes(item.id)}" data-save="${safe(item.id)}">♡</button></div><div class="product-info"><p class="product-category">${safe(categoryLabel(item.category))}</p><h3 class="product-name">${safe(item.title)}</h3><div class="product-meta"><span class="product-price">${money(item.price)}</span><span class="product-rating" aria-label="Rated ${safe(item.rating?.rate ?? 'new')} out of 5"><span aria-hidden="true">★</span> ${safe(item.rating?.rate ?? 'New')}</span></div><button class="add-button" type="button" data-add="${safe(item.id)}" aria-label="Add ${safe(item.title)} to bag">Add to bag +</button></div></article>`).join(''); $('#empty-state').hidden = list.length > 0; $('.result-count').textContent = `(${list.length})`; renderTable(); }
function renderTable() { $('#catalog-table').innerHTML = state.products.slice(0,8).map(item=>`<tr><td>${safe(item.title)}</td><td>${safe(categoryLabel(item.category))}</td><td>${money(item.price)}</td><td>★ ${safe(item.rating?.rate ?? 'New')}</td><td><button class="table-action" type="button" data-rename="${safe(item.id)}">Rename</button><button class="table-action danger" type="button" data-delete="${safe(item.id)}">Delete</button></td></tr>`).join(''); }
function renderCart() { const count = state.cart.reduce((total,row)=>total+row.quantity,0); $$('.cart-count').forEach(el=>{el.textContent=count;el.setAttribute('aria-label',`${count} ${count===1?'item':'items'}`)}); $('.cart-dialog-count').textContent=count?`(${count})`:''; $('#cart-total').textContent=money(state.cart.reduce((total,row)=>total+row.price*row.quantity,0)); $('#cart-items').innerHTML=state.cart.length?state.cart.map(row=>`<div class="cart-row"><img src="${safe(row.image)}" alt=""><div><strong>${safe(row.title)}</strong><small>${money(row.price)} each</small><div class="quantity-control"><button type="button" data-qty="${safe(row.id)}" data-delta="-1" aria-label="Remove one ${safe(row.title)}">−</button><span aria-label="Quantity ${row.quantity}">${row.quantity}</span><button type="button" data-qty="${safe(row.id)}" data-delta="1" aria-label="Add one ${safe(row.title)}">+</button></div></div><button class="remove-item" type="button" data-remove="${safe(row.id)}" aria-label="Remove ${safe(row.title)} from bag">×</button></div>`).join(''):'<p class="empty-state">Your bag is waiting for something lovely.</p>'; }
function addToCart(id) { const product=state.products.find(item=>String(item.id)===String(id)); if(!product)return; const row=state.cart.find(item=>String(item.id)===String(id)); row?row.quantity++:state.cart.push({...product,quantity:1}); saveStorage('northstar-cart',state.cart); renderCart(); announce(`${product.title} added to your bag.`); }
function setTheme(dark) { document.documentElement.classList.toggle('dark',dark); document.documentElement.dataset.theme=dark?'dark':'light'; $('.theme-toggle').setAttribute('aria-label',`Switch to ${dark?'light':'dark'} theme`); }
$$('.category-tab').forEach(button=>button.addEventListener('click',()=>{state.category=button.dataset.category;$$('.category-tab').forEach(tab=>{const selected=tab===button;tab.classList.toggle('selected',selected);tab.setAttribute('aria-pressed',String(selected));});renderProducts();}));
$$('[data-category-link]').forEach(link=>link.addEventListener('click',()=>{const value=link.dataset.categoryLink;state.category=value==='home'?"women's clothing":value;$('.category-tab.selected')?.classList.remove('selected');$$('.category-tab').forEach(tab=>{const selected=tab.dataset.category===state.category;tab.classList.toggle('selected',selected);tab.setAttribute('aria-pressed',String(selected));});}));
$('#search-input').addEventListener('input',event=>{state.query=event.target.value.trim().toLowerCase();renderProducts();});
$('#sort-select').addEventListener('change',event=>{state.sort=event.target.value;renderProducts();});
$('#product-grid').addEventListener('click',event=>{const add=event.target.closest('[data-add]');if(add)addToCart(add.dataset.add);const save=event.target.closest('[data-save]');if(save){const id=save.dataset.save;state.saved=state.saved.includes(id)?state.saved.filter(item=>item!==id):[...state.saved,id];saveStorage('northstar-saved',state.saved);renderProducts();announce(state.saved.includes(id)?'Saved for later.':'Removed from saved pieces.');}});
$('#cart-items').addEventListener('click',event=>{const qty=event.target.closest('[data-qty]');const remove=event.target.closest('[data-remove]');if(remove)state.cart=state.cart.filter(row=>String(row.id)!==remove.dataset.remove);if(qty){const row=state.cart.find(item=>String(item.id)===qty.dataset.qty);if(row)row.quantity+=Number(qty.dataset.delta);state.cart=state.cart.filter(row=>row.quantity>0);}saveStorage('northstar-cart',state.cart);renderCart();});
const dialog=$('#cart-dialog');$('.cart-trigger').addEventListener('click',()=>dialog.showModal());$('.close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close();});$('.checkout-button').addEventListener('click',()=>announce('Demo checkout only — no payment was collected.'));
$('.theme-toggle').addEventListener('click',()=>{const dark=!document.documentElement.classList.contains('dark');setTheme(dark);saveStorage('northstar-theme',dark?'dark':'light');});setTheme(readStorage('northstar-theme','light')==='dark');
$('#help-form').addEventListener('submit',event=>{event.preventDefault();if(!event.currentTarget.reportValidity())return;$('#form-status').textContent='Thanks — your demo message is ready. This project does not send email.';event.currentTarget.reset();});
$('#product-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;if(!form.reportValidity())return;const data=new FormData(form);try{const created=await createProduct({title:data.get('title').trim(),price:Number(data.get('price')),category:data.get('category'),description:'Added in the local learning demo.',image:'https://placehold.co/400x400/f0f1ec/375c46?text=Northstar'});state.products.unshift(created);renderProducts();$('#product-form-status').textContent=`${created.title} added to the catalog.`;form.reset();}catch(error){$('#product-form-status').textContent=`Could not add item: ${error.message}`;}});
$('#catalog-table').addEventListener('click',async event=>{const deleteButton=event.target.closest('[data-delete]');const renameButton=event.target.closest('[data-rename]');try{if(deleteButton){await deleteProduct(deleteButton.dataset.delete);state.products=state.products.filter(item=>String(item.id)!==deleteButton.dataset.delete);renderProducts();announce('Catalog item deleted.');}if(renameButton){const product=state.products.find(item=>String(item.id)===renameButton.dataset.rename);const title=window.prompt('Rename catalog item:',product?.title);if(title?.trim()){const updated=await updateProduct(renameButton.dataset.rename,{title:title.trim()});state.products=state.products.map(item=>String(item.id)===String(updated.id)?updated:item);renderProducts();announce('Catalog item renamed.');}}}catch(error){announce(`Catalog update failed: ${error.message}`);}});
$('.avatar').addEventListener('click',()=>{state.signedIn=!state.signedIn;saveStorage('northstar-demo-session',state.signedIn);$('.avatar').textContent=state.signedIn?'✓':'S';$('.avatar').setAttribute('aria-label',state.signedIn?'Sign out of demo account':'Sign in to demo account');announce(state.signedIn?'Signed in to the demo account. No account data was sent.':'Signed out of the demo account.');});
async function init(){renderCart();const grid=$('#product-grid');grid.setAttribute('aria-busy','true');const result=await getProducts({useExternal:state.external});state.products=result.products;$('#loading-skeleton').hidden=true;if(result.fallback){$('#catalog-status').hidden=false;$('#catalog-status').textContent='Showing a local sample collection. The live catalog could not be reached.';}renderProducts();}
init();
